// Shared inline styles and color tokens for bridge-app UI.
// No Tailwind dependency — pure inline React.CSSProperties.

export const COLOR = {
  bg: "#030712",
  surface: "#111827",
  border: "#1f2937",
  text: "#f3f4f6",
  muted: "#9ca3af",
  accent: "#3b82f6",
  green: "#22c55e",
  red: "#ef4444",
  yellow: "#f59e0b",
};

export const styles: Record<string, React.CSSProperties> = {
  app: {
    minHeight: "100vh",
    backgroundColor: COLOR.bg,
    color: COLOR.text,
    fontFamily: "system-ui, -apple-system, sans-serif",
    fontSize: 14,
  },
  loading: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    minHeight: "100vh",
    backgroundColor: COLOR.bg,
    color: COLOR.muted,
  },
  screen: {
    maxWidth: 700,
    margin: "0 auto",
    padding: "2rem 1.5rem",
  },
  heading: {
    fontSize: 22,
    fontWeight: 700,
    margin: "0 0 0.25rem",
  },
  subtext: {
    color: COLOR.muted,
    margin: "0 0 1.5rem",
    fontSize: 13,
  },
  form: {
    display: "flex",
    flexDirection: "column",
    gap: "1rem",
  },
  label: {
    display: "flex",
    flexDirection: "column",
    gap: "0.35rem",
    fontSize: 13,
    color: COLOR.muted,
    fontWeight: 500,
  },
  input: {
    backgroundColor: COLOR.surface,
    border: `1px solid ${COLOR.border}`,
    borderRadius: 6,
    padding: "0.5rem 0.75rem",
    color: COLOR.text,
    fontSize: 14,
    outline: "none",
  },
  button: {
    backgroundColor: COLOR.accent,
    color: "#fff",
    border: "none",
    borderRadius: 6,
    padding: "0.6rem 1.25rem",
    fontSize: 14,
    fontWeight: 600,
    cursor: "pointer",
    marginTop: "0.5rem",
    alignSelf: "flex-start",
  },
  buttonDisabled: {
    backgroundColor: "#374151",
    color: COLOR.muted,
    border: "none",
    borderRadius: 6,
    padding: "0.6rem 1.25rem",
    fontSize: 14,
    fontWeight: 600,
    cursor: "not-allowed",
    marginTop: "0.5rem",
    alignSelf: "flex-start",
  },
  buttonSecondary: {
    backgroundColor: COLOR.surface,
    color: COLOR.text,
    border: `1px solid ${COLOR.border}`,
    borderRadius: 6,
    padding: "0.6rem 1.25rem",
    fontSize: 14,
    fontWeight: 600,
    cursor: "pointer",
    alignSelf: "flex-start",
  },
  successMsg: {
    backgroundColor: "#052e16",
    border: `1px solid #166534`,
    color: COLOR.green,
    borderRadius: 6,
    padding: "0.5rem 0.75rem",
    fontSize: 13,
  },
  errorMsg: {
    backgroundColor: "#1c0000",
    border: `1px solid #7f1d1d`,
    color: COLOR.red,
    borderRadius: 6,
    padding: "0.5rem 0.75rem",
    fontSize: 13,
  },
  errorBanner: {
    display: "flex",
    alignItems: "center",
    gap: "0.5rem",
    backgroundColor: "#1c0000",
    border: `1px solid #7f1d1d`,
    color: COLOR.red,
    padding: "0.5rem 1rem",
    fontSize: 13,
    position: "sticky",
    top: 0,
    zIndex: 10,
  },
  errorClose: {
    background: "none",
    border: "none",
    color: COLOR.red,
    fontSize: 18,
    cursor: "pointer",
    lineHeight: 1,
    padding: 0,
  },
  inputRow: {
    display: "flex",
    gap: "0.5rem",
    alignItems: "center",
  },
  browseButton: {
    backgroundColor: COLOR.surface,
    color: COLOR.text,
    border: `1px solid ${COLOR.border}`,
    borderRadius: 6,
    padding: "0.5rem 0.75rem",
    fontSize: 13,
    fontWeight: 500,
    cursor: "pointer",
    whiteSpace: "nowrap",
    flexShrink: 0,
  } as React.CSSProperties,
  dropdowns: {
    display: "flex",
    flexDirection: "column",
    gap: "0.9rem",
    marginBottom: "1.5rem",
  },
  dropdownGroup: {
    display: "flex",
    flexDirection: "column",
    gap: "0.3rem",
  },
  dropdownLabel: {
    fontSize: 12,
    fontWeight: 600,
    color: COLOR.muted,
    textTransform: "uppercase",
    letterSpacing: "0.05em",
  },
  select: {
    backgroundColor: COLOR.surface,
    border: `1px solid ${COLOR.border}`,
    borderRadius: 6,
    padding: "0.5rem 0.75rem",
    color: COLOR.text,
    fontSize: 14,
    outline: "none",
    cursor: "pointer",
  },
  filesPanel: {
    backgroundColor: COLOR.surface,
    border: `1px solid ${COLOR.border}`,
    borderRadius: 8,
    overflow: "hidden",
    marginBottom: "1.5rem",
  },
  filesHeading: {
    fontSize: 13,
    fontWeight: 600,
    color: COLOR.muted,
    padding: "0.75rem 1rem",
    borderBottom: `1px solid ${COLOR.border}`,
    margin: 0,
    textTransform: "uppercase",
    letterSpacing: "0.05em",
  },
  shopRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "0.75rem",
    padding: "0.75rem 1rem",
    borderBottom: `1px solid ${COLOR.border}`,
  },
  shopInfo: {
    display: "flex",
    flexDirection: "column",
    gap: "0.15rem",
  },
  shopName: {
    fontWeight: 600,
    fontSize: 14,
  },
  fileCount: {
    fontSize: 12,
    color: COLOR.muted,
  },
  shopAction: {
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-end",
    gap: "0.25rem",
  },
  dlButton: {
    backgroundColor: COLOR.green,
    color: "#000",
    border: "none",
    borderRadius: 6,
    padding: "0.4rem 0.9rem",
    fontSize: 13,
    fontWeight: 600,
    cursor: "pointer",
  },
  dlButtonBusy: {
    backgroundColor: "#374151",
    color: COLOR.muted,
    border: "none",
    borderRadius: 6,
    padding: "0.4rem 0.9rem",
    fontSize: 13,
    fontWeight: 600,
    cursor: "wait",
  },
  dlButtonDone: {
    backgroundColor: "#052e16",
    color: COLOR.green,
    border: `1px solid #166534`,
    borderRadius: 6,
    padding: "0.4rem 0.9rem",
    fontSize: 13,
    fontWeight: 600,
    cursor: "default",
  },
  dlButtonError: {
    backgroundColor: "#1c0000",
    color: COLOR.red,
    border: `1px solid #7f1d1d`,
    borderRadius: 6,
    padding: "0.4rem 0.9rem",
    fontSize: 13,
    fontWeight: 600,
    cursor: "pointer",
  },
  dlMsgOk: {
    fontSize: 11,
    color: COLOR.green,
    maxWidth: 200,
    textAlign: "right",
    wordBreak: "break-all",
  },
  dlMsgError: {
    fontSize: 11,
    color: COLOR.red,
    maxWidth: 200,
    textAlign: "right",
    wordBreak: "break-all",
  },
  loadingText: {
    color: COLOR.muted,
    fontSize: 13,
    marginBottom: "1rem",
  },
  hintText: {
    color: COLOR.muted,
    fontSize: 13,
    marginBottom: "1rem",
  },
  footer: {
    display: "flex",
    alignItems: "center",
    gap: "1rem",
    color: COLOR.muted,
    fontSize: 12,
    marginTop: "auto",
    paddingTop: "1rem",
    borderTop: `1px solid ${COLOR.border}`,
    flexWrap: "wrap",
  },
  refreshLink: {
    background: "none",
    border: "none",
    color: COLOR.accent,
    fontSize: 12,
    cursor: "pointer",
    padding: 0,
    textDecoration: "underline",
  },
  folderRow: {
    display: "flex",
    flexDirection: "column",
    gap: "0.35rem",
    padding: "0.75rem 1rem",
    borderBottom: `1px solid ${COLOR.border}`,
  } as React.CSSProperties,
  folderLabel: {
    fontSize: 12,
    fontWeight: 600,
    color: COLOR.muted,
    textTransform: "uppercase",
    letterSpacing: "0.05em",
  } as React.CSSProperties,
  folderHint: {
    margin: 0,
    fontSize: 11,
    color: COLOR.muted,
  },
  folderWarning: {
    backgroundColor: "#1c1000",
    border: `1px solid #78350f`,
    color: COLOR.yellow,
    borderRadius: 5,
    padding: "0.4rem 0.6rem",
    fontSize: 12,
  },
  folderErrorText: {
    fontSize: 12,
    color: COLOR.red,
  },
  updateSection: {
    marginTop: "0.5rem",
    display: "flex",
    flexDirection: "column",
    gap: "0.75rem",
  } as React.CSSProperties,
  updateDivider: {
    height: 1,
    backgroundColor: COLOR.border,
    marginBottom: "0.25rem",
  },
  updateAvailableBox: {
    backgroundColor: "#1c1400",
    border: `1px solid #78350f`,
    borderRadius: 6,
    padding: "0.75rem 1rem",
    display: "flex",
    flexDirection: "column",
    gap: "0.5rem",
  } as React.CSSProperties,
  updateAvailableTitle: {
    fontWeight: 600,
    color: COLOR.yellow,
    fontSize: 14,
  },
  updateNotes: {
    color: COLOR.muted,
    fontSize: 12,
    whiteSpace: "pre-wrap",
    maxHeight: 120,
    overflowY: "auto",
  } as React.CSSProperties,
  updateMsgOk: {
    fontSize: 13,
    color: COLOR.green,
  },
  updateMsgError: {
    fontSize: 13,
    color: COLOR.red,
  },
  updateBannerBar: {
    display: "flex",
    alignItems: "center",
    gap: "0.5rem",
    backgroundColor: "#1c1400",
    border: `1px solid #78350f`,
    color: COLOR.yellow,
    padding: "0.5rem 1rem",
    fontSize: 13,
    position: "sticky",
    top: 0,
    zIndex: 10,
  } as React.CSSProperties,
  updateProgressBox: {
    backgroundColor: "#0a1628",
    border: `1px solid #1e3a5f`,
    borderRadius: 6,
    padding: "0.75rem 1rem",
    display: "flex",
    flexDirection: "column",
    gap: "0.5rem",
  } as React.CSSProperties,
  updateProgressLabel: {
    fontSize: 13,
    color: COLOR.text,
  },
  updateProgressTrack: {
    height: 6,
    backgroundColor: COLOR.border,
    borderRadius: 3,
    overflow: "hidden",
  },
  updateProgressFill: {
    height: "100%",
    backgroundColor: COLOR.accent,
    borderRadius: 3,
    transition: "width 0.2s ease",
  } as React.CSSProperties,
  updateProgressHint: {
    fontSize: 11,
    color: COLOR.muted,
    fontStyle: "italic",
  },
};
